import argparse
import hashlib
import json
import logging
import os
import warnings
import sys
from pathlib import Path
from pymongo import ReplaceOne

from dotenv import load_dotenv
from openai import AzureOpenAI
from pymongo import MongoClient

warnings.filterwarnings(
    "ignore", message="You appear to be connected to a CosmosDB cluster"
)

load_dotenv()
logging.basicConfig(level=logging.INFO, format="%(message)s")
logging.getLogger("httpx").setLevel(logging.WARNING)
log = logging.getLogger(__name__)

parser = argparse.ArgumentParser(description="Embed and upload chunks to MongoDB.")
parser.add_argument(
    "--input_json",
    type=Path,
    required=True,
    help="Path to the chunks.json file generated by chunk.py",
)
parser.add_argument(
    "--original_pdf",
    type=Path,
    required=True,
    help="Path to the original source file (e.g., PDF) for metadata extraction",
)
parser.add_argument(
    "--base_dir",
    default="data/pdf",
    help="root folder to ingest and base for metadata path parsing",
)
parser.add_argument(
    "--source_type_depth",
    type=int,
    default=0,
    help="folder depth for source_type (0-indexed, excluding filename)",
)
parser.add_argument(
    "--author_depth",
    type=int,
    default=1,
    help="folder depth for author (-1 to disable)",
)
parser.add_argument(
    "--fips_depth",
    type=int,
    default=-1,
    help="folder depth for fips code (-1 to disable)",
)
parser.add_argument(
    "--embedding_model", default=os.getenv("AZURE_EMBEDDING_MODEL_NAME")
)
parser.add_argument("--azure_endpoint", default=os.getenv("AZURE_EMBEDDING_ENDPOINT"))
parser.add_argument("--azure_api_key", default=os.getenv("AZURE_EMBEDDING_API_KEY"))
parser.add_argument("--azure_api_version", default=os.getenv("AZURE_EMBEDDING_VERSION"))
parser.add_argument(
    "--mongo_connection_string", default=os.getenv("MONGO_CONNECTION_STRING")
)
parser.add_argument("--db_name", default=os.getenv("DB_NAME"))
parser.add_argument("--db_container", default=os.getenv("DB_RAG_CONTAINER"))
parser.add_argument(
    "--batch_size",
    type=int,
    default=8,
    help="embedding batch size (set lower if embedding model rate limited)",
)
parser.add_argument(
    "--dry_run",
    action="store_true",
    help="simulate processing without embedding or writing to the database",
)

args = parser.parse_args()

openai_client = AzureOpenAI(
    azure_endpoint=args.azure_endpoint,
    api_key=args.azure_api_key,
    api_version=args.azure_api_version,
)
container = MongoClient(args.mongo_connection_string)[args.db_name][args.db_container]


def file_sha256(file_path: Path) -> str:
    """Hash the source file's bytes so callers can detect content changes."""
    h = hashlib.sha256()
    with Path(file_path).open("rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def path_metadata(file_path):
    """Return (rel_path_str, source_type, author, fips) from folder structure."""
    try:
        rel = Path(file_path).relative_to(args.base_dir)
        parts = rel.parts[:-1]

        source_type = (
            parts[args.source_type_depth]
            if args.source_type_depth < len(parts)
            else "general"
        )
        author = (
            parts[args.author_depth]
            if args.author_depth != -1 and args.author_depth < len(parts)
            else "Unknown"
        )
        fips = (
            parts[args.fips_depth]
            if args.fips_depth != -1 and args.fips_depth < len(parts)
            else None
        )
        return str(rel), source_type, author, fips
    except ValueError:
        return str(file_path), "general", "Unknown", None


def main():
    log.info(f"Preparing upload for: {args.original_pdf}")

    if not args.input_json.exists():
        log.error(f"  JSON file not found: {args.input_json}")
        sys.exit(1)

    try:
        chunks = json.loads(args.input_json.read_text(encoding="utf-8"))
    except Exception as e:
        log.error(f"  Failed to parse JSON: {e}")
        sys.exit(1)

    if not chunks:
        log.warning("  Skipping: no chunks found in JSON (empty document).")
        sys.exit(1)

    if not args.original_pdf.exists():
        log.error(f"  Source file not found: {args.original_pdf}")
        sys.exit(1)

    rel_path, source_type, author, fips = path_metadata(args.original_pdf)
    source_file = str(args.original_pdf)
    source_hash = file_sha256(args.original_pdf)

    log.info(
        f"  {len(chunks)} chunks loaded. Extracted metadata - Source: {source_type}, Author: {author}, FIPS: {fips}"
    )

    if args.dry_run:
        log.info("  [DRY RUN] Skipping embedding and database upload.")
        preview_chunk = chunks[0]["text"][:100].replace("\n", " ")
        log.info(
            f"  [DRY RUN PREVIEW] source={source_type} | fips={fips} | text={preview_chunk}..."
        )
        return

    log.info("  Embedding...")
    texts_to_embed = [c["text"] for c in chunks]
    embeddings = []

    try:
        for i in range(0, len(texts_to_embed), args.batch_size):
            resp = openai_client.embeddings.create(
                model=args.embedding_model,
                input=texts_to_embed[i : i + args.batch_size],
            )
            embeddings.extend(item.embedding for item in resp.data)
    except Exception as e:
        log.error(f"  Embedding failed: {e}")
        sys.exit(1)

    docs = []
    for i, (chunk_data, embedding) in enumerate(zip(chunks, embeddings)):
        meta = chunk_data["metadata"]

        doc = {
            "_id": chunk_data["id"],
            "chunk": chunk_data["text"],
            "contentHash": meta.get("hash", ""),
            "embedding": embedding,
            "sourceFile": source_file,
            "sourceHash": source_hash,
            "source": author,
            "sourceType": source_type,
            "chunkIndex": i,
            "pageNumbers": meta.get("pages", []),
            "pageRange": meta.get("page_range", None),
            "sectionPath": meta.get("section_path", ""),
            "tokens": meta.get("tokens", 0),
            "length": meta.get("length", 0),
        }

        if fips is not None:
            doc["fips"] = fips

        docs.append(doc)

    log.info("  Uploading to MongoDB...")
    try:
        new_chunk_ids = [doc["_id"] for doc in docs]

        container.delete_many(
            {"sourceFile": source_file, "_id": {"$nin": new_chunk_ids}}
        )

        operations = [ReplaceOne({"_id": doc["_id"]}, doc, upsert=True) for doc in docs]
        result = container.bulk_write(operations, ordered=False)

        log.info(f"  Done. Upserted {len(docs)} chunks.")
    except Exception as e:
        log.error(f"  MongoDB write failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
